// Global using directives

global using UnmappedAds = LPCGIBCKCLO;
global using UnmappedAnims = MBLIOKEDHHB;
global using UnmappedBlock = KBNFBEFCJGO;
global using UnmappedBlocks = GIMNNPMAKNJ;
global using UnmappedCam = BLNKDHIGFAN;
global using UnmappedController = BJMGCKGNCHO;
global using UnmappedControls = HKJOAJOKOIJ;
global using UnmappedControls_Switch = LPDBINKMCPP;
global using UnmappedDoor = OGAJMOPCPLJ;
global using UnmappedGlobals = NAEEIFNFBBO;
global using UnmappedItem = GGKBLABCJFN;
global using UnmappedItems = HAPFAOIMGOL;
global using UnmappedKeyboard = MOIHOCAMOOE;
global using UnmappedMatch = FFCEGMEAIBP;
global using UnmappedMenu = AKFIIKOMPLL;
global using UnmappedMenus = LIPNHOMGGHF;
global using UnmappedMeter = DLNHHGFNIIG;
global using UnmappedParticle = MEHJAJJNHLL;
global using UnmappedParticles = ALIGLHEIAGO;
global using UnmappedPlayer = DFOGOCNBECG;
global using UnmappedPlayers = NJBJIIIACEP;
global using UnmappedPromo = NEGAFEHECNL;
global using UnmappedSaveSystem = GLPGLJAJJOP;
global using UnmappedSound = CHLPMKEGJBJ;
global using UnmappedSprites = MCDCDEBALPI;
global using UnmappedTab = GLFLKKANOBF;
global using UnmappedTaunt = BAMPCDDGJDM;
global using UnmappedTextures = PFKAPGFJKHH;
global using UnmappedWeapon = GDFKEAMIOAG;
global using UnmappedWeapons = JFLEBEBCGFA;
global using UnmappedWindow = JBGEBIDPBOK;
global using HarmonyLib;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using System.IO;
global using UnityEngine;
global using HTCCL.Internal;
global using HTCCL.Utils;
global using static HTCCL.Utils.TextureUtils;
global using static HTCCL.Utils.MenuUtils;
global using static HTCCL.Content.CustomContent;
global using static HTCCL.Utils.FileNameUtils;
global using static HTCCL.Utils.ArrayUtils;
global using static HTCCL.Utils.LogUtils;
global using static HTCCL.Utils.DataSharing;